import { parseStrokeConfig } from './stroke-config.ts';
import type { StrokeConfig } from './tokens.ts';
import { isIconSize, type IconSize } from './tokens.ts';

/** Marker appended to the name of ComponentSets generated by the plugin. */
export const GENERATED_SUFFIX = '[generated]';

/**
 * Structured reason why an icon selection is invalid.
 * Replaces the previous error-string matching (which was fragile, e.g. the
 * '24×24px' vs '24x24px' mismatch between sandbox and UI).
 */
export type InvalidReason =
  | 'not-a-component'
  | 'already-generated'
  | 'no-24x24-variant'
  | 'not-24x24'
  | 'no-strokes'
  | 'empty';

export interface IconValidation {
  readonly name: string;
  readonly type: string;
  readonly valid: boolean;
  readonly reason: InvalidReason | null;
  /** Rendered size of the node when the reason is `not-24x24` (e.g. `16×16`). */
  readonly currentSize?: string;
}

export interface SelectionSummary {
  readonly total: number;
  readonly validCount: number;
  readonly invalidCount: number;
  readonly icons: readonly IconValidation[];
}

export interface DetectedStrokeVariable {
  readonly name: string;
  readonly size: IconSize;
  readonly collection: string;
  readonly key: string;
}

/** Messages sent from the plugin UI (iframe) to the sandbox. */
export type PluginMessage =
  | { type: 'validate' }
  | { type: 'generate' }
  | { type: 'cancel' }
  | { type: 'close' }
  | { type: 'get-stroke-config' }
  | { type: 'save-stroke-config'; config: StrokeConfig }
  | { type: 'reset-stroke-config' }
  | { type: 'detect-stroke-variables' }
  | { type: 'apply-stroke-variables'; variables: readonly DetectedStrokeVariable[] };

/** Messages sent from the sandbox to the plugin UI (iframe). */
export type UiMessage =
  | { type: 'validation-result'; result: IconValidation }
  | { type: 'validation-results'; summary: SelectionSummary }
  | { type: 'progress'; step: number; total: number; message: string }
  | { type: 'complete'; message: string }
  | { type: 'error'; message: string }
  | { type: 'stroke-config'; config: StrokeConfig }
  | { type: 'stroke-config-saved'; success: boolean }
  | { type: 'stroke-config-reset'; success: boolean; config: StrokeConfig }
  | { type: 'stroke-variables-detected'; variables: readonly DetectedStrokeVariable[] }
  | { type: 'stroke-variables-applied'; success: boolean; config: StrokeConfig }
  | { type: 'stroke-variables-error'; message: string };

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isDetectedStrokeVariable(value: unknown): value is DetectedStrokeVariable {
  return (
    isRecord(value) &&
    typeof value['name'] === 'string' &&
    isIconSize(value['size']) &&
    typeof value['collection'] === 'string' &&
    typeof value['key'] === 'string'
  );
}

function isDetectedStrokeVariableList(value: unknown): value is DetectedStrokeVariable[] {
  return Array.isArray(value) && value.every(isDetectedStrokeVariable);
}

/**
 * Parse a raw message received by the sandbox from the plugin UI.
 * Figma wraps the payload posted by the UI in a `pluginMessage` property,
 * but a bare payload is tolerated for convenience (matches legacy behavior).
 */
export function parsePluginMessage(input: unknown): PluginMessage | null {
  if (!isRecord(input)) {
    return null;
  }
  // Input is a record: either it wraps the payload in `pluginMessage` or it is the payload itself.
  const raw = isRecord(input['pluginMessage']) ? input['pluginMessage'] : input;
  switch (raw['type']) {
    case 'validate':
    case 'generate':
    case 'cancel':
    case 'close':
    case 'get-stroke-config':
    case 'reset-stroke-config':
    case 'detect-stroke-variables':
      return { type: raw['type'] };
    case 'save-stroke-config': {
      const config = parseStrokeConfig(raw['config']);
      return config ? { type: 'save-stroke-config', config } : null;
    }
    case 'apply-stroke-variables': {
      const variables = raw['variables'];
      return isDetectedStrokeVariableList(variables)
        ? { type: 'apply-stroke-variables', variables }
        : null;
    }
    default:
      return null;
  }
}

/** Parse a raw message received by the plugin UI from the sandbox. */
export function parseUiMessage(input: unknown): UiMessage | null {
  if (!isRecord(input)) {
    return null;
  }
  switch (input['type']) {
    case 'validation-result': {
      const result = input['result'];
      return isRecord(result) &&
        typeof result['name'] === 'string' &&
        isInvalidReason(result['reason'])
        ? {
            type: 'validation-result',
            result: {
              name: result['name'],
              type: typeof result['type'] === 'string' ? result['type'] : '',
              valid: result['valid'] === true,
              reason: result['valid'] === true ? null : result['reason'],
              currentSize:
                typeof result['currentSize'] === 'string' ? result['currentSize'] : undefined,
            },
          }
        : null;
    }
    case 'validation-results': {
      const summary = input['summary'];
      if (
        !isRecord(summary) ||
        typeof summary['total'] !== 'number' ||
        typeof summary['validCount'] !== 'number' ||
        typeof summary['invalidCount'] !== 'number' ||
        !Array.isArray(summary['icons']) ||
        !summary['icons'].every(isIconValidation)
      ) {
        return null;
      }
      return {
        type: 'validation-results',
        summary: {
          total: summary['total'],
          validCount: summary['validCount'],
          invalidCount: summary['invalidCount'],
          icons: summary['icons'],
        },
      };
    }
    case 'progress': {
      const { step, total, message } = input;
      return typeof step === 'number' && typeof total === 'number' && typeof message === 'string'
        ? { type: 'progress', step, total, message }
        : null;
    }
    case 'complete': {
      return typeof input['message'] === 'string'
        ? { type: 'complete', message: input['message'] }
        : null;
    }
    case 'error': {
      return typeof input['message'] === 'string'
        ? { type: 'error', message: input['message'] }
        : null;
    }
    case 'stroke-config': {
      const config = parseStrokeConfig(input['config']);
      return config ? { type: 'stroke-config', config } : null;
    }
    case 'stroke-config-saved': {
      return typeof input['success'] === 'boolean'
        ? { type: 'stroke-config-saved', success: input['success'] }
        : null;
    }
    case 'stroke-config-reset': {
      const config = parseStrokeConfig(input['config']);
      return typeof input['success'] === 'boolean' && config
        ? { type: 'stroke-config-reset', success: input['success'], config }
        : null;
    }
    case 'stroke-variables-detected': {
      return isDetectedStrokeVariableList(input['variables'])
        ? { type: 'stroke-variables-detected', variables: input['variables'] }
        : null;
    }
    case 'stroke-variables-applied': {
      const config = parseStrokeConfig(input['config']);
      return typeof input['success'] === 'boolean' && config
        ? { type: 'stroke-variables-applied', success: input['success'], config }
        : null;
    }
    case 'stroke-variables-error': {
      return typeof input['message'] === 'string'
        ? { type: 'stroke-variables-error', message: input['message'] }
        : null;
    }
    default:
      return null;
  }
}

function isIconValidation(value: unknown): value is IconValidation {
  return isRecord(value) && typeof value['name'] === 'string' && isInvalidReason(value['reason']);
}

function isInvalidReason(value: unknown): value is InvalidReason {
  return (
    value === 'not-a-component' ||
    value === 'already-generated' ||
    value === 'no-24x24-variant' ||
    value === 'not-24x24' ||
    value === 'no-strokes' ||
    value === 'empty' ||
    value === null
  );
}
