name: Publish Packages

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

concurrency:
  group: publish-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # for OIDC
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
          cache: 'yarn'

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_DEPLOY_KEY_IOS" > ~/.ssh/id_ed25519_ios
          echo "$SSH_DEPLOY_KEY_ANDROID" > ~/.ssh/id_ed25519_android
          chmod 600 ~/.ssh/id_ed25519_ios
          chmod 600 ~/.ssh/id_ed25519_android
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          cat > ~/.ssh/config << EOF
          # Host name should always match the github repository one
          Host ios-design-system
            HostName github.com
            User git
            IdentityFile ~/.ssh/id_ed25519_ios
            IdentitiesOnly yes

          # Host name should always match the github repository one
          Host android-design-system
            HostName github.com
            User git
            IdentityFile ~/.ssh/id_ed25519_android
            IdentitiesOnly yes
          EOF
          chmod 600 ~/.ssh/config
        env:
          SSH_DEPLOY_KEY_IOS: ${{ secrets.SSH_DEPLOY_KEY_IOS }}
          SSH_DEPLOY_KEY_ANDROID: ${{ secrets.SSH_DEPLOY_KEY_ANDROID }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Publish missing package versions
        if: >-
          github.event_name == 'push' ||
          (github.event_name == 'pull_request' &&
           github.event.pull_request.head.repo.full_name == github.repository &&
           contains(github.event.pull_request.labels.*.name, 'dev'))
        run: yarn ci:publish
        env:
          GITHUB_CI_CONFIG: ${{ toJson(github) }}
          KCHAT_WEBHOOK_ID: ${{ secrets.KCHAT_WEBHOOK_ID }}
          CI_PULL_REQUEST_AUTH_TOKEN_MOBILE: ${{ secrets.CI_PULL_REQUEST_AUTH_TOKEN_MOBILE }}

      - name: Publish missing package versions (dry-run for fork PR)
        if: >-
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.full_name != github.repository &&
          contains(github.event.pull_request.labels.*.name, 'dev')
        run: yarn ci:publish
        env:
          GITHUB_CI_CONFIG: ${{ toJson(github) }}
          CI_PUBLISH_DRY_RUN: 'true'
          ENV_SHOULD_NOTIFY: 'false'
